const FLAG_BUCKET_URL = "https://ydvggllbrswfchgjhjhr.supabase.co/storage/v1/object/public/flags";

// Nationality values used by roster records mapped to their exact bucket files.
// Covers common demonyms across every confederation so a fictional roster for
// any future prospect can draw from a wide pool without needing shared-code
// edits. A few bucket filenames carry upstream misspellings (e.g. Morroco,
// Romenia, Cambodja) — the keys below use correct English demonyms regardless.
const FLAG_FILES: Record<string, string> = {
  // North & Central America, Caribbean
  American: "USA.png",
  Canadian: "Canada.png",
  Mexican: "Mexico.png",
  "Costa Rican": "CostaRica.png",
  Honduran: "Honduras.png",
  Guatemalan: "Guatemala.png",
  Panamanian: "Panama.png",
  Salvadoran: "ElSalvador.png",
  Nicaraguan: "Nicaragua.png",
  Jamaican: "Jamaica.png",
  Cuban: "Cuba.png",
  Dominican: "DominicanRepublic.png",
  Haitian: "Haiti.png",
  Trinidadian: "TrinidadTobado.png",

  // South America
  Brazilian: "Brazil.png",
  Argentine: "Argentina.png",
  Chilean: "Chile.png",
  Colombian: "Colombia.png",
  Peruvian: "Peru.png",
  Uruguayan: "Uruguay.png",
  Paraguayan: "Paraguay.png",
  Bolivian: "Bolivia.png",
  Venezuelan: "Venezuela.png",
  Ecuadorian: "Ecuador.png",
  Guyanese: "Guyana.png",
  Surinamese: "Suriname.png",

  // Western & Northern Europe
  English: "England.png",
  British: "UnitedKingdom.png",
  Welsh: "Wales.png",
  Irish: "Ireland.png",
  French: "France.png",
  German: "Germany.png",
  Italian: "Italy.png",
  Spanish: "Spain.png",
  Portuguese: "Portugal.png",
  Dutch: "Netherlands.png",
  Belgian: "Belgium.png",
  Swiss: "Switzerland.png",
  Austrian: "Austria.png",
  Danish: "Denmark.png",
  Swedish: "Sweden.png",
  Norwegian: "Norway.png",
  Finnish: "Finland.png",
  Icelandic: "Iceland.png",
  Luxembourgish: "Luxembourg.png",

  // Central & Eastern Europe
  Polish: "Poland.png",
  Czech: "CzechRepublic.png",
  Slovak: "Slovakia.png",
  Hungarian: "Hungary.png",
  Romanian: "Romenia.png",
  Bulgarian: "Bulgaria.png",
  Greek: "Greece.png",
  Turkish: "Turkey.png",
  Croatian: "Croatia.png",
  Serbian: "Serbia.png",
  Slovenian: "Slovenia.png",
  Bosnian: "BosniaHerzegovina.png",
  Montenegrin: "Montenegro.png",
  Macedonian: "Macedonia.png",
  Albanian: "Albania.png",
  Ukrainian: "Ukraine.png",
  Russian: "Russia.png",
  Belarusian: "Belarus.png",
  Lithuanian: "Lithuania.png",
  Latvian: "Latvia.png",
  Estonian: "Estonia.png",
  Georgian: "Georgia.png",
  Armenian: "Armenia.png",
  Azerbaijani: "Azerbaijan.png",
  Cypriot: "Cyprus.png",
  Maltese: "Malta.png",

  // Africa
  Moroccan: "Morroco.png",
  Algerian: "Algeria.png",
  Tunisian: "Tunisia.png",
  Egyptian: "Egypt.png",
  Libyan: "Libya.png",
  Nigerian: "Nigeria.png",
  Ghanaian: "Ghana.png",
  Senegalese: "Senegal.png",
  Ivorian: "CoteD'Ivoire.png",
  Cameroonian: "Cameroon.png",
  Malian: "Mali.png",
  Kenyan: "Kenya.png",
  Ethiopian: "Ethiopia.png",
  Ugandan: "Uganda.png",
  Tanzanian: "Tanzania.png",
  "South African": "SouthAfrica.png",
  Zambian: "Zambia.png",
  Zimbabwean: "Zimbabwe.png",
  Angolan: "Angola.png",
  Congolese: "CongoDemocraticRepublic.png",
  Gabonese: "Gabon.png",
  Beninese: "Benin.png",
  Togolese: "Togo.png",
  "Sierra Leonean": "SierraLeone.png",
  Liberian: "Liberia.png",
  Guinean: "Guinea.png",
  Burkinabe: "BurkinaFaso.png",
  Nigerien: "Niger.png",
  Chadian: "Chad.png",
  Sudanese: "Sudan.png",
  Rwandan: "Rwanda.png",
  Namibian: "Namibia.png",
  Mozambican: "Mozambique.png",
  Malagasy: "Madagascar.png",
  Mauritian: "Mauritius.png",

  // Asia & Middle East
  Japanese: "Japan.png",
  Chinese: "China.png",
  "South Korean": "SouthKorea.png",
  "North Korean": "NorthKorea.png",
  Indian: "India.png",
  Pakistani: "Pakistan.png",
  Bangladeshi: "Bangladesh.png",
  "Sri Lankan": "SriLanka.png",
  Nepali: "Nepal.png",
  Vietnamese: "Vietnam.png",
  Thai: "Thailand.png",
  Indonesian: "Indonesia.png",
  Malaysian: "Malaysia.png",
  Filipino: "Philippines.png",
  Singaporean: "Singapore.png",
  Cambodian: "Cambodja.png",
  Laotian: "Laos.png",
  Burmese: "Myanmar-Burma.png",
  Mongolian: "Mongolia.png",
  Kazakh: "Kazakhstan.png",
  Uzbek: "Uzbekistan.png",
  Afghan: "Afghanistan.png",
  Iranian: "Iran.png",
  Iraqi: "Iraq.png",
  Israeli: "Israel.png",
  Palestinian: "Palestine.png",
  Jordanian: "Jordan.png",
  Lebanese: "Lebanon.png",
  Syrian: "Syria.png",
  Saudi: "SaudiArabia.png",
  Emirati: "UnitedArabEmirates.png",
  Qatari: "Qatar.png",
  Kuwaiti: "Kuwait.png",
  Bahraini: "Bahrain.png",
  Omani: "Oman.png",
  Yemeni: "Yemen.png",
  Taiwanese: "Taiwan.png",

  // Oceania
  Australian: "Australia.png",
  "New Zealander": "NewZealand.png",
  Fijian: "Fiji.png",
  "Papua New Guinean": "PapuaNewGuinea.png",
  Samoan: "Samoa.png",
  Tongan: "Tonga.png",
};

export function getFlagUrl(nationality: string): string | undefined {
  const filename = FLAG_FILES[nationality.trim()];
  return filename ? `${FLAG_BUCKET_URL}/${encodeURIComponent(filename)}` : undefined;
}
